# -*- coding: utf-8 -*-

"""
    ontraportlib.models.charge_now_25_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2017
"""

class ChargeNow25Enum(object):

    """Implementation of the 'ChargeNow25' enum.

    TODO: type enum description here.

    Attributes:
        CHARGENOW: TODO: type description here.
        CHARGELOG: TODO: type description here.

    """

    CHARGENOW = 'chargeNow'

    CHARGELOG = 'chargeLog'

