# -*- coding: utf-8 -*-

"""
    ontraportlib.models.charge_now_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2017
"""

class ChargeNowEnum(object):

    """Implementation of the 'ChargeNow' enum.

    TODO: type enum description here.

    Attributes:
        CHARGENOW: TODO: type description here.

    """

    CHARGENOW = 'chargeNow'

