# -*- coding: utf-8 -*-

"""
    ontraportlib.models.format_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2017
"""

class FormatEnum(object):

    """Implementation of the 'format' enum.

    TODO: type enum description here.

    Attributes:
        BYID: TODO: type description here.
        BYNAME: TODO: type description here.

    """

    BYID = 'byId'

    BYNAME = 'byName'

