# -*- coding: utf-8 -*-

"""
    ontraportlib.models.notification_type_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2017
"""

class NotificationTypeEnum(object):

    """Implementation of the 'NotificationType' enum.

    TODO: type enum description here.

    Attributes:
        NOTIFICATION: TODO: type description here.

    """

    NOTIFICATION = 'notification'

