# -*- coding: utf-8 -*-

"""
    ontraportlib.models.order
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2017
"""
import  ontraportlib.models.address
import  ontraportlib.models.offer
import  ontraportlib.models.payer
import  ontraportlib.models.base_model

class Order(ontraportlib.models.base_model.BaseModel):

    """Implementation of the 'Order' model.

    TODO: type model description here.

    Attributes:
        contact_id (int): TODO: type description here.
        object_id (int): TODO: type description here.
        affiliate_id (int): Affiliate ID.
        billing_address (Address): TODO: type description here.
        charge_now (ChargeNowEnum): TODO: type description here.
        gateway_id (int): Gateway ID.
        invoice_template (int): Invoice template ID.
        offer (Offer): TODO: type description here.
        payer (Payer): TODO: type description here.

    """

    def __init__(self, 
                 contact_id = None,
                 object_id = None,
                 affiliate_id = None,
                 billing_address = None,
                 charge_now = None,
                 gateway_id = None,
                 invoice_template = None,
                 offer = None,
                 payer = None):
        """Constructor for the Order class"""
        
        # Initialize members of the class
        self.contact_id = contact_id
        self.object_id = object_id
        self.affiliate_id = affiliate_id
        self.billing_address = billing_address
        self.charge_now = charge_now
        self.gateway_id = gateway_id
        self.invoice_template = invoice_template
        self.offer = offer
        self.payer = payer

        # Create a mapping from Model property names to API property names
        self.names = {
            "contact_id" : "contact_id",
            "object_id" : "objectID",
            "affiliate_id" : "affiliate_id",
            "billing_address" : "billing_address",
            "charge_now" : "chargeNow",
            "gateway_id" : "gateway_id",
            "invoice_template" : "invoice_template",
            "offer" : "offer",
            "payer" : "payer",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            contact_id = dictionary.get("contact_id")
            object_id = dictionary.get("objectID")
            affiliate_id = dictionary.get("affiliate_id")
            billing_address = ontraportlib.models.address.Address.from_dictionary(dictionary.get("billing_address")) if dictionary.get("billing_address") else None
            charge_now = dictionary.get("chargeNow")
            gateway_id = dictionary.get("gateway_id")
            invoice_template = dictionary.get("invoice_template")
            offer = ontraportlib.models.offer.Offer.from_dictionary(dictionary.get("offer")) if dictionary.get("offer") else None
            payer = ontraportlib.models.payer.Payer.from_dictionary(dictionary.get("payer")) if dictionary.get("payer") else None
            # Return an object of this model
            return cls(contact_id,
                       object_id,
                       affiliate_id,
                       billing_address,
                       charge_now,
                       gateway_id,
                       invoice_template,
                       offer,
                       payer)
