# -*- coding: utf-8 -*-

"""
    ontraportlib.models.payer
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2017
"""
import  ontraportlib.models.base_model

class Payer(ontraportlib.models.base_model.BaseModel):

    """Implementation of the 'Payer' model.

    TODO: type model description here.

    Attributes:
        ccnumber (string): TODO: type description here.
        code (string): CVV code.
        expire_month (int): Expiration month (1-12).
        expire_year (int): Expiration year (four-digit year, e.g. 2018).

    """

    def __init__(self, 
                 ccnumber = None,
                 code = None,
                 expire_month = None,
                 expire_year = None):
        """Constructor for the Payer class"""
        
        # Initialize members of the class
        self.ccnumber = ccnumber
        self.code = code
        self.expire_month = expire_month
        self.expire_year = expire_year

        # Create a mapping from Model property names to API property names
        self.names = {
            "ccnumber" : "ccnumber",
            "code" : "code",
            "expire_month" : "expire_month",
            "expire_year" : "expire_year",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            ccnumber = dictionary.get("ccnumber")
            code = dictionary.get("code")
            expire_month = dictionary.get("expire_month")
            expire_year = dictionary.get("expire_year")
            # Return an object of this model
            return cls(ccnumber,
                       code,
                       expire_month,
                       expire_year)
