# -*- coding: utf-8 -*-

"""
    ontraportlib.models.price
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2017
"""
import  ontraportlib.models.base_model

class Price(ontraportlib.models.base_model.BaseModel):

    """Implementation of the 'Price' model.

    TODO: type model description here.

    Attributes:
        id (int): TODO: type description here.
        payment_count (int): TODO: type description here.
        price (float): TODO: type description here.
        unit (UnitEnum): TODO: type description here.

    """

    def __init__(self, 
                 id = None,
                 payment_count = None,
                 price = None,
                 unit = None):
        """Constructor for the Price class"""
        
        # Initialize members of the class
        self.id = id
        self.payment_count = payment_count
        self.price = price
        self.unit = unit

        # Create a mapping from Model property names to API property names
        self.names = {
            "id" : "id",
            "payment_count" : "payment_count",
            "price" : "price",
            "unit" : "unit",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            id = dictionary.get("id")
            payment_count = dictionary.get("payment_count")
            price = dictionary.get("price")
            unit = dictionary.get("unit")
            # Return an object of this model
            return cls(id,
                       payment_count,
                       price,
                       unit)
