# -*- coding: utf-8 -*-

"""
    ontraportlib.models.setup_fee_when_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2017
"""

class SetupFeeWhenEnum(object):

    """Implementation of the 'SetupFeeWhen' enum.

    TODO: type enum description here.

    Attributes:
        IMMEDIATELY: TODO: type description here.
        AFTER_TRIAL: TODO: type description here.
        ON_DATE: TODO: type description here.

    """

    IMMEDIATELY = 'immediately'

    AFTER_TRIAL = 'after_trial'

    ON_DATE = 'on_date'

