# -*- coding: utf-8 -*-

"""
    ontraportlib.models.sort_dir_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2017
"""

class SortDirEnum(object):

    """Implementation of the 'SortDir' enum.

    TODO: type enum description here.

    Attributes:
        ASC: TODO: type description here.
        DESC: TODO: type description here.

    """

    ASC = 'asc'

    DESC = 'desc'

