# -*- coding: utf-8 -*-

"""
    ontraportlib.models.subscription_unit_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2017
"""

class SubscriptionUnitEnum(object):

    """Implementation of the 'SubscriptionUnit' enum.

    TODO: type enum description here.

    Attributes:
        DAY: TODO: type description here.
        WEEK: TODO: type description here.
        MONTH: TODO: type description here.
        QUARTER: TODO: type description here.
        YEAR: TODO: type description here.

    """

    DAY = 'day'

    WEEK = 'week'

    MONTH = 'month'

    QUARTER = 'quarter'

    YEAR = 'year'

