# -*- coding: utf-8 -*-

"""
    ontraportlib.models.type_13_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2017
"""

class Type13Enum(object):

    """Implementation of the 'Type13' enum.

    TODO: type enum description here.

    Attributes:
        SINGLE: TODO: type description here.
        SUBSCRIPTION: TODO: type description here.
        ONE_TIME: TODO: type description here.
        PAYMENT_PLAN: TODO: type description here.

    """

    SINGLE = 'single'

    SUBSCRIPTION = 'subscription'

    ONE_TIME = 'one_time'

    PAYMENT_PLAN = 'payment_plan'

