# -*- coding: utf-8 -*-

"""
    ontraportlib.models.type_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2017
"""

class TypeEnum(object):

    """Implementation of the 'Type' enum.

    TODO: type enum description here.

    Attributes:
        PLAINTEXT: TODO: type description here.

    """

    PLAINTEXT = 'plaintext'

