# -*- coding: utf-8 -*-

"""
   ontraportlib.configuration

   This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/14/2017
"""
from .api_helper import APIHelper

class Configuration(object):

    """A class used for configuring the SDK by a user.
    
    This class need not be instantiated and all properties and methods
	are accessible without instance creation.
    
    """

    # The base Uri for API calls
    base_uri = 'https://api.ontraport.com/1'


