# -*- coding: utf-8 -*-

"""
    ontraportlib.ontraport_client

    This file was automatically generated by APIMATIC BETA v2.0 on 11/14/2017
"""
from .decorators import lazy_property
from .controllers.forms_controller import FormsController
from .controllers.landing_page_controller import LandingPageController
from .controllers.messages_controller import MessagesController
from .controllers.objects_controller import ObjectsController
from .controllers.tasks_controller import TasksController
from .controllers.transactions_controller import TransactionsController

class ONTRAPORTClient(object):

    @lazy_property
    def forms(self):
        return FormsController()

    @lazy_property
    def landing_page(self):
        return LandingPageController()

    @lazy_property
    def messages(self):
        return MessagesController()

    @lazy_property
    def objects(self):
        return ObjectsController()

    @lazy_property
    def tasks(self):
        return TasksController()

    @lazy_property
    def transactions(self):
        return TransactionsController()



